title: My Portfolio Site
email: premmaheshwari089@gmail.com
description: >-
  Welcome to my personal portfolio. Explore my projects, resume, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prem-mahesh.github.io/my-github-pages-site" # the base hostname & protocol for your site
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# Site settings
author:
  name: Prem Maheshwari
  avatar: /assets/images/your-photo.jpg
  email: premmaheshwari089@gmail.com
  url: https://prem-mahesh.github.io/my-github-pages-site

# Social settings
social:
  github: yourusername
  linkedin: yourusername
  email: your-email@example.com

