title: My Portfolio Site
email: premmaheshwari089@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal portfolio. Explore my projects, resume, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Prem-mahesh.github.io/my-github-pages-site" # the base hostname & protocol for your site
theme: jekyll-theme-cayman

